project:
  type: website
  output-dir: docs

website:
  title: "clairetimm.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: All About Me
      - href: interests.qmd
        text: Interests
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Blog posts

format:
  html:
    theme: materia
    css: styles.css
    toc: true



