project:
  type: website
  output-dir: docs 
  
website:
  title: "Claire Timm"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - interests.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

